version: '3.8'

services:

  backend:
    build: ./backend
    container_name: imperium-backend
    restart: always
    ports:
      - "8084:8086"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/imperium_fitness
      SPRING_DATASOURCE_USERNAME: mplf
      SPRING_DATASOURCE_PASSWORD: 12345678

      
volumes:
  db_data:
