events {}

http {

  upstream backend {
    server backend:8086;
  }

  upstream web {
    server web:8085;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend/;
    }
  }
}